### ISSUE TITLE
Errors while parsing DBC

### ISSUE THREAD

**Issue by gianpyc** [ebroecker/canmatrix#330] opened 2019-03-16 13:20 UTC
I get an error when parsing a DBC similar to:
`BA_ "Period [ms]" BO_ 1234567890 3000;`
and 
`BA_ "Signal Age [ms]" SG_ 1234567890 sometext 5000;`

Is this a bug or an issue on the DBC file?
Thanks

**Comment by altendky** [comment] 2019-03-16 18:24
Are you able to share the problematic .dbc?  Regardless, please share what version of canmatrix you are running and also the full traceback.

Cheers,
-kyle

**Comment by gianpyc** [comment] 2019-03-16 18:45
Sorry I cannot share the dbc.
I installed canmatrix today using pip install canmatrix on mac os. I wasn't able to understand the version but pip download from:
`https://files.pythonhosted.org/packages/a5/a1/b2bd32bb0e0898e8e80f5e3ef5f42c54c3dea95d9df05929d8b2a2e71b17/canmatrix-0.7-py2.py3-none-any.whl`
plus other dependencies.

This is the command I run:
`canconvert -v --frames=MY_ECU_NAME mydb.dbc target.dbc`

The traceback is composed by a set of errors like:
```
error with line no: 810
BA_ "Period [ms]" BO_ 1234567890 3000;
...
error with line no: 998
BA_ "Signal Age [ms]" SG_ 1234567890 sometext 5000;

Plus other similar errors
```
and

```
INFO - convert - done
INFO - convert - Exporting target.dbc ... 
INFO - copy - Copying Frame MY_ECU_NAME
Traceback (most recent call last):
  File "/usr/local/bin/canconvert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/canmatrix/convert.py", line 402, in main
    convert(infile, outfileName, **cmdlineOptions.__dict__)
  File "/usr/local/lib/python2.7/site-packages/canmatrix/convert.py", line 61, in convert
    canmatrix.copy.copyFrame(frame, dbs[name], db)
  File "/usr/local/lib/python2.7/site-packages/canmatrix/copy.py", line 134, in copyFrame
    copyBU(sourceBU, sourceDb, targetDb)
  File "/usr/local/lib/python2.7/site-packages/canmatrix/copy.py", line 49, in copyBU
    deepcopy(attribute), deepcopy(sourceDb.buDefines[attribute].definition))
KeyError: u'Node Address'
```
Hope this helps. 

Cheers

**Comment by ebroecker** [comment] 2019-03-17 15:35
@gianpyc 
Thank you very much for your bug report.

I could identify one problem... 
Canmatrix has currently problems with braces `[`,`]` in attributes.

I have a local fix for this issue here.
could you please try:
`pip install git+https://github.com/ebroecker/canmatrix@iss330#egg=canmatrix`
and give feedback?

Thanks

**Comment by gianpyc** [comment] 2019-03-17 17:19
with this command my repo is not updated and I get:
```
Requirement already satisfied: canmatrix from git+https://github.com/ebroecker/canmatrix@iss330#egg=canmatrix in /usr/local/lib/python2.7/site-packages (0.7)
Requirement already satisfied: bitstruct in /usr/local/lib/python2.7/site-packages (from canmatrix) (6.0.0)
Requirement already satisfied: attrs>=18.1.0 in /usr/local/lib/python2.7/site-packages (from canmatrix) (19.1.0)
Requirement already satisfied: pathlib2 in /usr/local/lib/python2.7/site-packages (from canmatrix) (2.3.3)
Requirement already satisfied: future in /usr/local/lib/python2.7/site-packages (from canmatrix) (0.17.1)
Requirement already satisfied: scandir; python_version < "3.5" in /usr/local/lib/python2.7/site-packages (from pathlib2->canmatrix) (1.10.0)
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (from pathlib2->canmatrix) (1.11.0)
```

So, I updated manually the file dpc.py but I wasn't able to update test_dbc.py. This last file seems different with the version that you modified. 

Btw, when running the command again I got less errors but this traceback:
```
INFO - convert - Importing my.dbc ... 
INFO - convert - done

INFO - convert - Exporting target.dbc ... 
INFO - copy - Copying Frame My_ECU
Traceback (most recent call last):
  File "/usr/local/bin/canconvert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/canmatrix/convert.py", line 402, in main
    convert(infile, outfileName, **cmdlineOptions.__dict__)
  File "/usr/local/lib/python2.7/site-packages/canmatrix/convert.py", line 61, in convert
    canmatrix.copy.copyFrame(frame, dbs[name], db)
  File "/usr/local/lib/python2.7/site-packages/canmatrix/copy.py", line 134, in copyFrame
    copyBU(sourceBU, sourceDb, targetDb)
  File "/usr/local/lib/python2.7/site-packages/canmatrix/copy.py", line 49, in copyBU
    deepcopy(attribute), deepcopy(sourceDb.buDefines[attribute].definition))
KeyError: u'Node Address'
```

Thanks for your help

**Comment by ebroecker** [comment] 2019-03-17 17:52
Thanks for trying the fix.

without digging in it seems a bit like there is no `definition` for `Node Address`.
Could you verify that in `mydb.dbc` there is a definition like:
`BA_DEF BU_ "Node Address" STRING;`

?

**Comment by gianpyc** [comment] 2019-03-17 18:07
I have this definition:
`BA_DEF_ BU_  "Node Address" INT 0 255;`
and not that one suggested.

Trying this instead:
`BA_DEF BU_ "Node Address" STRING;`

Same error

Thanks

**Comment by ebroecker** [comment] 2019-03-17 18:49
Thanks for looking into your dbc.

`BA_DEF_ BU_  "Node Address" INT 0 255;`

is surely right (the other one with `STRING` is wrong!)


I'm a bit clueless, the code which fails does nothing really complicated:

https://github.com/ebroecker/canmatrix/blob/5ccf848377b56d3786b6c4336164dd7f7e78ff20/src/canmatrix/copy.py#L46-L49

walk through all attributes of the given ECU and copy these attributes and their definitons to the new matrix. And it looks like the definition is not found. But you found it in your dbc...

I'll play a bit around, maybe I'll find some hint...

**Comment by ebroecker** [comment] 2019-03-17 19:25
could you please again fetch the `dbc.py` from the branch above and test?

**Comment by gianpyc** [comment] 2019-03-17 20:01
Now I get this traceback:
Traceback (most recent call last):
```
  File "/usr/local/bin/canconvert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/canmatrix/convert.py", line 402, in main
    convert(infile, outfileName, **cmdlineOptions.__dict__)
  File "/usr/local/lib/python2.7/site-packages/canmatrix/convert.py", line 43, in convert
    dbs = canmatrix.formats.loadp(infile, **options)
  File "/usr/local/lib/python2.7/site-packages/canmatrix/formats.py", line 64, in loadp
    return load(fileObject, importType, key, flatImport, **options)
  File "/usr/local/lib/python2.7/site-packages/canmatrix/formats.py", line 76, in load
    dbs[key] = moduleInstance.load(fileObject, **options)
  File "/usr/local/lib/python2.7/site-packages/canmatrix/dbc.py", line 721, in load
    db.ecus.append(canmatrix.Ecu(ele))
AttributeError: 'CanMatrix' object has no attribute 'ecus'
```

Thanks

**Comment by ebroecker** [comment] 2019-03-17 22:11
Hi @gianpyc 

we did heavy refactoring the last days [`ecus` is the new `boardUnits`]. 
So please either try to get the whole branch `iss330` or adapt only the *change* of the `dbc.py` ...

**Comment by gianpyc** [comment] 2019-03-18 09:10
Thanks,
I updated canmatrix applying last changes and now I get this traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/canconvert", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/convert.py", line 411, in main
    convert(infile, out_file_name, **cmdlineOptions.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/convert.py", line 42, in convert
    dbs = canmatrix.formats.loadp(infile, **options)
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/formats/__init__.py", line 68, in loadp
    return load(fileObject, import_type, key, flat_import, **options)
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/formats/__init__.py", line 81, in load
    dbs[key] = module_instance.load(file_object, **options)  # type: ignore
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/formats/dbc.py", line 794, in load
    if tempba.group(1).strip().startswith("BO_ "):
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by ebroecker** [comment] 2019-03-18 20:06
seems you have a lot of special characters in attribute names ... could you please try once more?

**Comment by gianpyc** [comment] 2019-03-19 09:06
No I get this traceback :(

```
Traceback (most recent call last):
  File "/usr/local/bin/canconvert", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/convert.py", line 411, in main
    convert(infile, out_file_name, **cmdlineOptions.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/convert.py", line 42, in convert
    dbs = canmatrix.formats.loadp(infile, **options)
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/formats/__init__.py", line 68, in loadp
    return load(fileObject, import_type, key, flat_import, **options)
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/formats/__init__.py", line 81, in load
    dbs[key] = module_instance.load(file_object, **options)  # type: ignore
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/formats/dbc.py", line 798, in load
    print('group3', temp.group(3))
IndexError: no such group
```

From a quick debug I saw that  temp.group(2) and  temp.group(3) are empty. Only  temp.group(1) has a content.

Thanks for your support

**Comment by ebroecker** [comment] 2019-03-19 09:14
Hi @gianpyc,
Thanks for testing.

Did you upgrade branch "iss330" or did you only apply 
8057942 ?

I activated the global "try" "except" again in 33f02590, this should print out the failing input line in dbc. 
With this line, I hope I can reproduce the issue...

**Comment by gianpyc** [comment] 2019-03-19 09:28
Before I did `git pull` but I saw that it didn't change a lot the `dbc.py` code so I manually made 
https://github.com/ebroecker/canmatrix/commit/80579423e389fce8741b35d881a673f0d9e012b6

Now, I replaced all the code that I have in dbc.py with last one you updated:
https://raw.githubusercontent.com/ebroecker/canmatrix/33f0259031bdfad555fd4d8220d2d85e2903a815/src/canmatrix/formats/dbc.py

And I get this traceback:
```
INFO - convert - Importing MYdbc.dbc ... 
INFO - convert - done

INFO - convert - Exporting target.dbc ... 
INFO - copy - Copying Frame MY_ECU
Traceback (most recent call last):
  File "/usr/local/bin/canconvert", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/convert.py", line 411, in main
    convert(infile, out_file_name, **cmdlineOptions.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/convert.py", line 61, in convert
    canmatrix.copy.copy_frame(frame_to_copy.arbitration_id, dbs[name], db)
  File "/usr/local/lib/python2.7/dist-packages/canmatrix/copy.py", line 175, in copy_frame
    copy.deepcopy(attribute), copy.deepcopy(source_db.frame_defines[attribute].definition))
KeyError: u'Period [ms]'
```

Thanks

**Comment by ebroecker** [comment] 2019-03-19 10:00
ok, thanks, I'm gonna work on this, looks quite similar to the initial bug...

**Comment by ebroecker** [comment] 2019-03-19 23:21
ok, it's worth another try

**Comment by gianpyc** [comment] 2019-03-20 09:03
Much better, now I reach the end of the operation if even this errors occurs during the parsing:
```
BA_ "Description" BU_ ECU "SOME TEXT";
BA_ "Accuracy" SG_ Number_ID TEXT "+/- 0.12 V";
BA_ "Accuracy" SG_  Number_ID Some_TEXT "+/- 0.9 bar";
BA_ "Accuracy" SG_ Number_ID Text "+/- 10.2 at 55.1%";
```
Plus other similar errors

In addition, I'd like to ask if with canmatrix it is possible to extract signal frame in its hex format, as it'd be sent by an ECU in the CAN payload, by setting manually the signal value or by having all combination for those signal values. It'd be very nice to have as feature.

Thanks a lot for your support

**Comment by ebroecker** [comment] 2019-03-20 20:23
@gianpyc 
thanks for your patience.
I did more repairing on your provided reports.

Yes - it is possible to decode can-data and to encode can-data.

have a look at Frame.decode 
https://github.com/ebroecker/canmatrix/blob/eb6d4f4d1cb5cc82d91b849cab5a32ef12d336d2/src/canmatrix/canmatrix.py#L1090

and Frame.encode
https://github.com/ebroecker/canmatrix/blob/eb6d4f4d1cb5cc82d91b849cab5a32ef12d336d2/src/canmatrix/canmatrix.py#L987

**Comment by gianpyc** [comment] 2019-03-21 08:51
Thanks for your patient too :)
Still some errors to fix like:
```
BA_ "Description" BU_ ECU "Some Some Some Text";
BA_ "Description" BU_ ECU "Some Some Text";
BA_ "Description" BU_ ECU "Some Text";
BA_ "Description" BU_ ECU_NAME "Some Text";
```

Also thanks for the encode/decode functions. Is there a way to invoke using command line? Or in case is there a python example in which a I can load my dbc and encode signals of an ECU?

**Comment by ebroecker** [comment] 2019-03-21 19:50
ok, I think, I made it worse with one of the first commits and now have to repair it again...
Again a new fix for your issue...

for encoding/decoding: What is your usecase, can you describe a bit, maybe I create a feature for you.
otherwise decoding/encoding is not that complicated.
Have a look at 
https://github.com/ebroecker/canmatrix/blob/development/src/canmatrix/tests/test_frame_decoding.py
and
https://github.com/ebroecker/canmatrix/blob/development/src/canmatrix/tests/test_frame_encoding.py

**Comment by gianpyc** [comment] 2019-03-21 20:51
Fantastic now it works without any errors! Thanks a lot 👍 
Do you think to integrate the changes in the main branches?

For encoding my wish is to have a command line script in which I could set as parameter the name of the frame, e.g., testFrame1 in your example dbc, and the script prompts me to insert the value for each signal and at the end it provides me the encoded frame.

Cheers

**Comment by ebroecker** [comment] 2019-03-22 19:12
yes the changes will be merged to mainline, this will take a few days, because I want to do some review and cleanup.

I also going to create some example tool to create one frame

**Comment by ebroecker** [comment] 2019-03-22 20:27
I created an example tool in branch `cliEncodeOneFrame`
usage like:
`encodeFrame -f testFrameName nameOfDbc.dbc`

**Comment by gianpyc** [comment] 2019-03-22 23:02
Thanks a lot for encodeFrame cli! It is what I needed. Can I ask you to do a similar thing for the decode, in which I pass the frame in hex format, the dbc and the frame is decoded.

Really thanks

**Comment by ebroecker** [comment] 2019-03-24 20:16
Added `decodeFrame`to `cliEncodeOneFrame`

**Comment by gianpyc** [comment] 2019-03-25 12:11
Thanks a lot for all support you've done

**Comment by ebroecker** [comment] 2019-03-28 14:11
fixed

**Closed by ebroecker** 2019-03-28 14:11 UTC
