### ISSUE TITLE
Issue in converting an excel file to dbc

### ISSUE THREAD

**Issue by Jayanthdj** [ebroecker/canmatrix#367] opened 2019-05-31 05:22 UTC
Could you please help as I am facing issue in converting an excel files to dbc. I am attaching the screenshot
First file error
![image](https://user-images.githubusercontent.com/33441532/58683436-05f64400-8392-11e9-9f49-8296cc000cdb.png)
 second file error
![image](https://user-images.githubusercontent.com/33441532/58683464-24f4d600-8392-11e9-9e8c-339bc51a467c.png)

**Comment by Funth0mas** [comment] 2019-06-11 21:43
Could you please provide minimal example of such excel file?

**Comment by yuren1986** [comment] 2019-06-15 15:56
Hello Funth0mas,

 I also find the same issue report.

![image](https://user-images.githubusercontent.com/51859118/59553539-caca5680-8fc8-11e9-8d50-d588492eec5c.png)

So can we use the canconvert change the .xlsx file to .dbc ?

Hope your feedback, thanks.

**Comment by Funth0mas** [comment] 2019-06-15 20:07
Hi @yuren1986, both issues are pretty unrelated. The first has "incompatible" header whereas your table contains spaces in the cell, where canmatrix expects CAN ID ("ID" in the header). It must either contain valid hexadecimal CAN ID ended by "xh" or empty cell (really empty, not containing spaces not visible by eyes)

You can find example table under https://github.com/Funth0mas/canmatrix/blob/development/test/test.xls and https://github.com/Funth0mas/canmatrix/blob/development/test/test.xlsx  I see possible discrepancy with plain non-extended can IDs

If it doesn't help you, let provide your table (simplified, with modified data if they're secret) for analysis.

**Comment by yuren1986** [comment] 2019-06-16 13:17
Hello Funth0mas,
Thanks for your helping. I had checked your suggestion the test.xlsx can be transformed to dbc file, but the dbc file can't open.

The error as following, i think the reason is caused by the send type. 
![image](https://user-images.githubusercontent.com/51859118/59564476-f2c5c280-9079-11e9-880e-6a01857d7eb3.png)

And I use the TEST file cmTemplate.xlsx change to the .dbc , and I found the CAN ID has been changed from 123h to 12h.
![image](https://user-images.githubusercontent.com/51859118/59564634-b004ea00-907b-11e9-98f2-4dd01705439b.png)

So maybe the data information has been changed wrong by data type between transformation.]

Do you find the same issue also?

**Comment by ebroecker** [comment] 2019-06-16 14:58
Looks like the define ist Missing. I'll have a Look on it

**Comment by Funth0mas** [comment] 2019-06-17 07:17
There is indeed a discrepancy in parsing standard can ID (123h) versus extended (12345xh), in both cases are stripped last two letters, effectively leading to trimming 123h to 0x12.

**Comment by yuren1986** [comment] 2019-06-17 11:18
@Funth0mas @ebroecker I have got it.  How can we use this? Actually this extend mode and normal  mode doesnt be combined in one DBC. I will verify  with this on independently. Thanks for your analyze, hope you have a nice day.

**Comment by Funth0mas** [comment] 2019-06-17 11:38
If you need to convert standard can IDs, than simply try to write them as 123sh in the excel to get 0x123 in the dbc. It's just a hotfix until the bug will be fixed. You can safely mix standard and extended ids in single file.

**Comment by ebroecker** [comment] 2019-06-24 13:27
@yuren1986 

there are 2 issues here:
1. corrupt arbitration ids
2. the "GenMsgSendType"

for 1. I'll provide a fix soon, till than use the workarround presented aboven (from  @Funth0mas)
for 2: use `--deleteFrameAttributes=GenMsgSendType`
`python -m canmatrix.cli.convert test\test.xls foo.dbc --deleteFrameAttributes=GenMsgSendType`

2: only is a problem, if no send-type (e.g. cyclic) is defined anywhere in xls(x)

**Comment by ebroecker** [comment] 2019-06-25 13:54
@yuren1986 could you try branch `iss367` please?

should fix (1.)

Thanks

**Comment by ebroecker** [comment] 2019-07-15 11:54
(1. ) should be fixed with #377  (in development branch since 1ccdb5d39b175ea869c43d780a1cf01cbe8569f9)

**Closed** 2019-08-19 12:29 UTC
Labels: bug

**Comment by Ederwardlu** [comment] 2022-03-29 07:12
There are something wrong as figure show when I try to convert xlsx to dbc 
![IMG_2251 小](https://user-images.githubusercontent.com/50871816/160554348-c247d6b6-02d6-4218-8e99-8308062c87d1.jpeg)
.
