### ISSUE TITLE
ARXML to XLS issue

### ISSUE THREAD

**Issue by mahanteshdh** [ebroecker/canmatrix#94] opened 2017-08-14 19:24 UTC
Hi I am using tool to convert arxml to xls, got this error, I am using following arxml version:

http://autosar.org/schema/r4.0 AUTOSAR_4-1-1.xsd" xmlns="http://autosar.org/schema/r4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> 

Attached error screen:

Is there size limitation?

![error_2](https://user-images.githubusercontent.com/31011446/29287701-603931ee-8104-11e7-9f34-48681212bfc4.jpg)
![error_1](https://user-images.githubusercontent.com/31011446/29287695-5c4139ba-8104-11e7-97e1-ebe1fc59fd98.jpg)

**Comment by ebroecker** [comment] 2017-08-14 20:30
You are using version 0.5? Your ARXML contains canFD-Frames right?
Please try dev-0.6-Branch.
It's a known issue of 0.5, that canfd is not supported (frames with more than 8 bytes are buggy in 0.5)

**Comment by mahanteshdh** [comment] 2017-08-15 11:48
Yes my arxml contains CAN FD frames. I installed dev-0.6 branch and i see below issue :
![image](https://user-images.githubusercontent.com/31011446/29314884-0c7eea6e-818e-11e7-9877-5f8b0fa9b915.png)

**Comment by ebroecker** [comment] 2017-08-15 19:03
OK, I fixed the error, but I guess it still doesn't do what it should do?

**Comment by mahanteshdh** [comment] 2017-08-15 19:59
I adopted your changes. Thank you! 
Now i am able to generate .dbc and .xls from my arxml.
but Min and Max value for signals seems to be incorrect and also message periodicity/cycle time is not extracted. Attached screen shot for reference
Min and Max value for a signal in arxml is -4096 and 4095 respectively but dbc and xls show 0 to 8191.

![image](https://user-images.githubusercontent.com/31011446/29333638-82bc7680-81d2-11e7-9af6-931e2934570d.png)

**Comment by ebroecker** [comment] 2017-08-15 20:43
the warning above "no datatype found" leads to missing min/max values.

I'm not sure how to fix this.
The problem is, that the datatype for the signal is not found.
Probably the datatype is references at another place in the arxml. 
But I have no idea where this could be.
Currently I search for the datatype in SYSTEM-SIGNAL which is reverenced by SIGNAL or I-SIGNAL.

You are not able so send me a sample (maybe email - not here)?

Best Regards

**Comment by mahanteshdh** [comment] 2017-08-16 12:56
If i open signal information in Autosar explorer tool from Vector, I can see datatype info and other info highlighted in red in attached screenshot. only cylce time/ periodicity found in PDU in other screen below : 
I do not have sample arxml, but I will try to strip out information from original and create sample.

![image](https://user-images.githubusercontent.com/31011446/29363949-ddb8941e-825f-11e7-805b-be3f1dad107c.png)


![image](https://user-images.githubusercontent.com/31011446/29364096-6bd954ae-8260-11e7-8ab9-aa75e7032fbd.png)

Thank you!

**Comment by ebroecker** [comment] 2017-08-16 14:11
Maybe you could look in the arxml and search for a xml-tag "DATA-TYPE-REF" and what's the parent tag named.

**Comment by mahanteshdh** [comment] 2017-08-16 16:06
I don't have DATA-TYPE-REF xml-tag in my arxml.

**Comment by ebroecker** [comment] 2017-08-16 19:41
OK, You are right. 
In AR4 there is no data-type-ref -- there are "BASE-TYPE-REF",  a "COMPU-METHOD-REF" and a "DATA-CONSTR-REF".
Currently canmatrix does **not** read these infos from AR4-Files.

give me some Time to get this working. 
How important is this for your needs?
Do you have a timelimit?

**Comment by mahanteshdh** [comment] 2017-08-16 20:06
I can wait, Appreciate your help!

**Comment by ebroecker** [comment] 2017-08-29 21:13
@mahanteshdh : maybe you could test again?
could be better now...

**Comment by mahanteshdh** [comment] 2017-09-27 13:16
I tested the new update, and found same issue with Min,Max, resolution and offset. Time period is also not extracted to XLS.

**Comment by mahanteshdh** [comment] 2017-09-27 13:16
Sorry for responding late.

**Comment by mahanteshdh** [comment] 2017-09-27 19:56
I see Min and Max value issue for signed values not for unsigned value.

**Comment by ebroecker** [comment] 2017-09-29 07:11
OK, thanx for the info.
I'm quite busy these days. 
May take some time since I'll have a closer look...

**Comment by ebroecker** [comment] 2017-12-13 21:28
sign extraction is currently not supported.
in ARXML I have to determin the base datatype and map them to "signed" or "unsigned".

**Comment by ebroecker** [comment] 2018-04-06 08:45
@mahanteshdh 
Do you have issues with the current implementation.
Should I have another look on the code or can I close this issue?

**Comment by ebroecker** [comment] 2018-08-16 09:25
please reopen, if still a problem

**Closed by ebroecker** 2018-08-16 09:25 UTC
Labels: bug
