### ISSUE TITLE
Error while converting a dbc file to any other format

### ISSUE THREAD

**Issue by aggarwalpiyush** [ebroecker/canmatrix#158] opened 2018-06-15 21:07 UTC
Error is:
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by aggarwalpiyush** [comment] 2018-06-28 23:04
Hi,
I have figured out the issue. The code is unable to handle following: "[ms]". So, when I replaced "[ms]" with "ms" in all places, it worked perfectly.
Thanks for the guidance.

**Comment by ebroecker** [comment] 2018-06-29 05:38
Hi,
thanks for this info.
What letters did these lines start with? This would help to fix the Bug.
thanks in advance

**Comment by ebroecker** [comment] 2018-08-11 22:09
sorry - I can't reproduce. 
Due lack of information, I have to close this issue.
It could be reopended, as soon as there are more infos about this issue.

**Closed by ebroecker** 2018-08-11 22:09 UTC
Labels: bug
