### ISSUE TITLE
Errors while parsing DBC with comma in enum attribute values

### ISSUE THREAD

**Issue by blem14** [ebroecker/canmatrix#263] opened 2018-11-29 14:33 UTC
Errors occur while parsing DBC with `,` as one of enum attribute values.
It is recognized as valid option by Vector CANdb++.

Occurs on develop (ed4a1d5c80d0a1a4e48fa8a8492a3a913f95c365), attributes are not collected.
On master (f9b84b834b1b93d849823a01d4bcea33b01f8866) errors does not occur, attributes are collected, but with invalid values - `['"Val1"', '"', '"']`.

Expected to get `['Val1', ',',]`

Errors:
> error with line no: 37
> b'BA_DEF_ "example0" ENUM "Val1",",";\r\n'
> error with line no: 38
> b'BA_DEF_ BO_ "example1" ENUM "Val1",",";\r\n'
> error with line no: 39
> b'BA_DEF_ SG_ "example2" ENUM "Val1",",";\r\n'
> error with line no: 41
> b'BA_DEF_ BU_ "example4" ENUM "Val1",",";\r\n'

Can be reproduced with DBC containig these lines:
> VERSION ""
> 
> 
> NS_ : 
> 	NS_DESC_
> 	CM_
> 	BA_DEF_
> 	BA_
> 	VAL_
> 	CAT_DEF_
> 	CAT_
> 	FILTER
> 	BA_DEF_DEF_
> 	EV_DATA_
> 	ENVVAR_DATA_
> 	SGTYPE_
> 	SGTYPE_VAL_
> 	BA_DEF_SGTYPE_
> 	BA_SGTYPE_
> 	SIG_TYPE_REF_
> 	VAL_TABLE_
> 	SIG_GROUP_
> 	SIG_VALTYPE_
> 	SIGTYPE_VALTYPE_
> 	BO_TX_BU_
> 	BA_DEF_REL_
> 	BA_REL_
> 	BA_DEF_DEF_REL_
> 	BU_SG_REL_
> 	BU_EV_REL_
> 	BU_BO_REL_
> 	SG_MUL_VAL_
> 
> BS_:
> 
> BU_:
> 
> 
> 
> 
> BA_DEF_  "example0" ENUM  "Val1",",";
> BA_DEF_ BO_  "example1" ENUM  "Val1",",";
> BA_DEF_ SG_  "example2" ENUM  "Val1",",";
> BA_DEF_ EV_  "example3" ENUM  "Val1",",";
> BA_DEF_ BU_  "example4" ENUM  "Val1",",";
> BA_DEF_DEF_  "example0" ",";
> BA_DEF_DEF_  "example1" ",";
> BA_DEF_DEF_  "example2" ",";
> BA_DEF_DEF_  "example3" ",";
> BA_DEF_DEF_  "example4" ",";
> 
>

**Comment by ebroecker** [comment] 2018-11-29 19:16
@blem14 
Thank you very much for your bug report.

Reports of this quality are easy for us to work on, because you provided everything we need to reproduce.

I'll just no start to fix this issue.

**Comment by ebroecker** [comment] 2018-12-04 07:16
@blem14 
could you try branch `iss263`. 
should fix this issue.

`pip install git+https://github.com/ebroecker/canmatrix@iss263` should do it...

**Comment by blem14** [comment] 2018-12-05 10:48
This fixes the issue for comma, however further tests with other special characters shows that space is causing error too, not sure if it was like that earlier.

I used following line to test special character compatibility within CANdb++:

> BA_DEF_ BO_  "example" ENUM  "Val 1","vector_leerstring",""," ","'","(",")","[","]","/","-","|","{","}",";",":","<",">",".","?","!","@","#","$","%","^","&","=","`","~";

Here is screenshot of the given line's option list in the CANdb++.
As you can see, "vector_leerstring" is used by the CANdb++ to store information about empty option. Upon opening file "" is also recognized as valid option, only to be replaced with "vector_leerstring" if DBC is saved.

Fun fact - CANdb++ allows multiple options of the same string, but I haven't tested it yet.

![example](https://user-images.githubusercontent.com/16246495/49508328-bae7f200-f882-11e8-8f26-b1bf4556ada0.png)

**Comment by ebroecker** [comment] 2018-12-05 12:08
@blem14 
Thanks for providing even more test data.
I'll work on it.

**Comment by ebroecker** [comment] 2018-12-05 19:13
@blem14 
should be fixed now also

**Comment by ebroecker** [comment] 2018-12-10 10:34
@blem14 
No problem, ..., gonna fix this soon

**Comment by ebroecker** [comment] 2018-12-10 19:23
fixed

**Comment by ebroecker** [comment] 2018-12-10 19:25
fixed

**Closed by ebroecker** 2018-12-10 19:25 UTC
Labels: bug
