### ISSUE TITLE
Value type 'is_signed': converting arxml to dbc

### ISSUE THREAD

**Issue by Mombox** [ebroecker/canmatrix#368] opened 2019-06-07 08:49 UTC

**Comment by ilazrak** [comment] 2019-06-07 09:03
@ebroecker 

'unsigned signals' in arxml become 'signed signals' after conversion to dbc,
which also affects the Min and Max values of the obtained signals...

        rawRange = 2 ** (self.size - (1 if self.**is_signed** else 0))
        return (
            factory(-rawRange if self.**is_signed** else 0),
            factory(rawRange - 1),

**Comment by Funth0mas** [comment] 2019-06-11 21:44
Could you please provide minimal example of such arxml file?

**Comment by ilazrak** [comment] 2019-06-24 07:52
[NewCluster_max_min.zip](https://github.com/ebroecker/canmatrix/files/3319776/NewCluster_max_min.zip)

@Funth0mas 
attached one Frame similar to my arxml data

thanks

**Comment by Funth0mas** [comment] 2019-08-02 08:14
Okay I accidentally reproduced the same issue with own ARXML :-) @ebroecker, there is some signed/unsigned guessing based on `BASE-TYPE` name. Instead, as described in https://www.autosar.org/fileadmin/user_upload/standards/adaptive/17-10/AUTOSAR_SWS_AdaptivePlatformTypes.pdf, we shall check for `<BASE-TYPE-ENCODING>` value:

 * `NONE` for unsigned integers
 * `2C` for signed integers "two's complement"
 * `IEEE754` for float32/float32
 * `BOOLEAN`

have you already some progress, or shall I try to fix it? I might find some time to do it.

**Comment by ebroecker** [comment] 2019-08-02 08:45
@Funth0mas 
You are probably right...
Well - you are welcome - if you find time - do fix this

**Comment by Funth0mas** [comment] 2019-08-08 21:09
@ilazrak please does the linear scale used in you example file make sense? There are
```
                      <COMPU-NUMERATOR>
                        <V>0</V>
                        <V>1</V>
                      </COMPU-NUMERATOR>
                      <COMPU-DENOMINATOR>
                        <V>0</V>
                        <V>1</V>
```
If I understand correctly that is a polynomial (0 + 1*x)/(0 + 1*x) = 1, that means constant one... unfortunately this also leads to divide-by-zero in canmatrix because it expects such function to be expressed simply as (1 + 0*x)/(1 + 0*x) => offset=1/1=1, scale=0/1=0.

**Comment by ebroecker** [comment] 2019-08-13 14:03
@iartez could you please try branch iss385?

Thanks

**Comment by ebroecker** [comment] 2019-08-19 10:40
fixed in development now.
Please reopen or open new issue if still not working as expected

**Closed by ebroecker** 2019-08-19 10:40 UTC

**Comment by Prabhu6296** [comment] 2021-01-25 11:29
> @ilazrak please does the linear scale used in you example file make sense? There are
> 
> ```
>                       <COMPU-NUMERATOR>
>                         <V>0</V>
>                         <V>1</V>
>                       </COMPU-NUMERATOR>
>                       <COMPU-DENOMINATOR>
>                         <V>0</V>
>                         <V>1</V>
> ```
> 
> If I understand correctly that is a polynomial (0 + 1_x)/(0 + 1_x) = 1, that means constant one... unfortunately this also leads to divide-by-zero in canmatrix because it expects such function to be expressed simply as (1 + 0_x)/(1 + 0_x) => offset=1/1=1, scale=0/1=0.

Could you please elaborate and explain the calculation of offset and scale value? It's a little confusing due to 1 and 0 values. Thanks in advance :) hope you will take some time to rectify this minuscule query of mine!

**Comment by Funth0mas** [comment] 2021-03-27 19:59
@Prabhu6296  you can find more information in https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TPS_SoftwareComponentTemplate.pdf , section "5.5.1.1    Category Values in the context of a CompuMethod". Than  search for `CompuNominatorDenominator`. 
The offset and scale is expressed os a 2nd order polynomial.
